// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2bM9LcMBQTOzckl6RXHJ3wKaTxgAjwqo',
    appId: '1:591636661500:web:4a4390ed2f3021ee5d4379',
    messagingSenderId: '591636661500',
    projectId: 'gymskie-2f289',
    authDomain: 'gymskie-2f289.firebaseapp.com',
    storageBucket: 'gymskie-2f289.firebasestorage.app',
    measurementId: 'G-K0FZSCDQK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYu4RnJnbHKzMTg5QczoMKKlnLBByGUfw',
    appId: '1:591636661500:android:b0f58c145225dfe35d4379',
    messagingSenderId: '591636661500',
    projectId: 'gymskie-2f289',
    storageBucket: 'gymskie-2f289.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6j9j7n2JNX1opxwvWXoP6X9dIVUqmp2Y',
    appId: '1:591636661500:ios:bec863f385a442a55d4379',
    messagingSenderId: '591636661500',
    projectId: 'gymskie-2f289',
    storageBucket: 'gymskie-2f289.firebasestorage.app',
    iosBundleId: 'com.example.geminiIoTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6j9j7n2JNX1opxwvWXoP6X9dIVUqmp2Y',
    appId: '1:591636661500:ios:bec863f385a442a55d4379',
    messagingSenderId: '591636661500',
    projectId: 'gymskie-2f289',
    storageBucket: 'gymskie-2f289.firebasestorage.app',
    iosBundleId: 'com.example.geminiIoTalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2bM9LcMBQTOzckl6RXHJ3wKaTxgAjwqo',
    appId: '1:591636661500:web:f03a8f2b295a41185d4379',
    messagingSenderId: '591636661500',
    projectId: 'gymskie-2f289',
    authDomain: 'gymskie-2f289.firebaseapp.com',
    storageBucket: 'gymskie-2f289.firebasestorage.app',
    measurementId: 'G-4X8DGX9KPX',
  );

}